### ISSUE TITLE
Retrying setup: '<=' not supported between instances of 'datetime.datetime' and 'float'

### ISSUE THREAD

**Issue by JamieB226** [Southern-Company-HA/southern-company-hacs#15]
## Version of the custom_component

The const.py file doesn't have a version, but i downloaded and installed it from GitHub on 2023-02-28.

## Configuration

I don't know where to get the component configuration yaml file.

## Describe the bug

It was working after I installed it on Feb 28th.  When March 1st came around, I was not getting data and the integration showed an error saying "Retrying setup: '<=' not supported between instances of 'datetime.datetime' and 'float'".  I tried uninstalling and re-installing the component in HA and no change.  I also confirmed this wasn't a "first day of the month" problem as it is still happening on March 2nd.

## Debug log

Logger: custom_components.southern_company_hacs.coordinator
Source: custom_components/southern_company_hacs/coordinator.py:139
Integration: Southern Company HACS ([documentation](https://github.com/Lash-L/southern-company-hacs), [issues](https://github.com/Lash-L/southern-company-hacs/issues))
First occurred: March 1, 2023 at 17:04:57 (783 occurrences)
Last logged: 11:34:59

Unexpected error fetching Southern Company Hacs data: '<=' not supported between instances of 'datetime.datetime' and 'float'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/southern_company_hacs/coordinator.py", line 61, in _async_update_data
    await self._insert_statistics()
  File "/config/custom_components/southern_company_hacs/coordinator.py", line 139, in _insert_statistics
    last_stats_time is not None and from_time <= last_stats_time
TypeError: '<=' not supported between instances of 'datetime.datetime' and 'float'

**Comment by Lash-L** [comment]
Yep - I knew this issue existed, statistics were changed in the last release for some optimizations, my dev branch had the changes, but I couldn't put it on hacs as then it would cause an issue as it was trying to do 2023.3 logic on a 2023.2 instance.

It should be fixed now with 0.1.4.

**Comment by chicagoandy** [comment]
I am still getting this with 0.1.5

**Comment by Lash-L** [comment]
> I am still getting this with 0.1.5

Did you restart after updating? I'm on 0.1.5 on my system and I'm not getting that issue. Try an uninstall and reinstall

**Comment by JamieB226** [comment]
I can confirm after removing, reinstalling, rebooting, and reconfiguring the energy dashboard, this is working for me.  The data is delayed two days but it pulling it in.

**Comment by Lash-L** [comment]
> I can confirm after removing, reinstalling, rebooting, and reconfiguring the energy dashboard, this is working for me.  The data is delayed two days but it pulling it in.

Okay so separate issue than the original.


Look at your hourly data on Georgia powers website. It seems Georgia power recently got slower with updating their energy information. 

The last piece of hourly data I have is March 3rd on Georgia powers website and March 3rd in home assistant as well.
If you have an extra day on ga powers website than you do on home assistant, then we have a problem. Otherwise, it is just a limitation of the data they make available and when they make it available

**Comment by JamieB226** [comment]
Understood.  I realize it's a separate issue and I assumed it was on GP's side.

**Comment by chicagoandy** [comment]
Yes, still getting it with 0.1.5.
Note the line numbers are off-by-one from what this defect shows:

2023-03-06 12:32:32.912 ERROR (MainThread) [custom_components.southern_company_hacs.coordinator] Unexpected error fetching Southern Company Hacs data: '<=' not supported between instances of 'float' and 'datetime.datetime'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
self.data = await self._async_update_data()
File "/config/custom_components/southern_company_hacs/coordinator.py", line 62, in _async_update_data
await self._insert_statistics()
File "/config/custom_components/southern_company_hacs/coordinator.py", line 141, in _insert_statistics
and from_time.timestamp() <= last_stats_time
TypeError: '<=' not supported between instances of 'float' and 'datetime.datetime'

**Comment by Lash-L** [comment]
> Yes, still getting it with 0.1.5.
> 
> Note the line numbers are off-by-one from what this defect shows:
> 
> 
> 
> 2023-03-06 12:32:32.912 ERROR (MainThread) [custom_components.southern_company_hacs.coordinator] Unexpected error fetching Southern Company Hacs data: '<=' not supported between instances of 'float' and 'datetime.datetime'
> 
> Traceback (most recent call last):
> 
> File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
> 
> self.data = await self._async_update_data()
> 
> File "/config/custom_components/southern_company_hacs/coordinator.py", line 62, in _async_update_data
> 
> await self._insert_statistics()
> 
> File "/config/custom_components/southern_company_hacs/coordinator.py", line 141, in _insert_statistics
> 
> and from_time.timestamp() <= last_stats_time
> 
> TypeError: '<=' not supported between instances of 'float' and 'datetime.datetime'

Are you on the latest version of HA? How Statistics work changed, you have to be on 2023.3

**Comment by chicagoandy** [comment]
Ah, that's it.   I typically wait for a .4 or .5 release before upgrading to the monthly.
