### ISSUE TITLE
Home Assistant 2023.6.0 Breaks Integration

### ISSUE THREAD

**Issue by rac146** [Southern-Company-HA/southern-company-hacs#37]
Seems the latest version of home assistant (2023.6.0) breaks the Southern Company HACS integration. Goes into a initializing/retry state. 

Log below:

<img width="1266" alt="image" src="https://github.com/Lash-L/southern-company-hacs/assets/6462376/67f78a5b-c6cb-46a8-9c5e-ffd10165a4c0">

**Comment by johnsmoses** [comment]
Also having this issue. I believe Python was upgraded in the last release? Unsure if that matters.

![Screenshot 2023-06-09 114352](https://github.com/Lash-L/southern-company-hacs/assets/18271633/c4e3fbb1-694e-41e4-86f2-e445b25a1431)
![Screenshot 2023-06-09 114628](https://github.com/Lash-L/southern-company-hacs/assets/18271633/c9cfe563-11a8-4e32-8832-9c458c2f977d)

**Comment by Lash-L** [comment]
Fixed in 0.1.9
