### ISSUE TITLE
2024.1.2 (seemingly) causes issues with authenitcation.

### ISSUE THREAD

**Issue by boomam** [Southern-Company-HA/southern-company-hacs#66]
## Version of the custom_component
0.1.9

## Describe the bug

Recent Home Assistant core update, 2024.1.2, caused a new notification in HA -  
`Integration requires reconfiguration, At least one of your integrations requires reconfiguration to continue functioning. Check it out.`.  
Upon clicking, or going to integrations, i can see that 'Southern Company Hacs' has a 'RECONFIGURE' button.  

Clicking this shows a window titled 'Southern Company HACS' and two unlabeled boxes. 
Assuming that its a login box, i enter my Southern Company login (which i have confirmed to be valid), and then get returned to the same window, with a new red box at the top, with the information `Invalid authentication`.

## Debug log
The log has no reference to this integration within it.

**Comment by jprost98** [comment]
I am getting this issue with 2024.1.1 as well.

**Comment by robertscheib** [comment]
I am also getting this error with 2024.1.5

**Comment by Responsible-User** [comment]
I too am getting this error. I reset my password with Southern Co and still have the same problem. I did not have any issues until the 2024.1.5 update.

**Comment by jprost98** [comment]
I actually got it working by changing my password, deleting the configuration, reinstalling it, then signing in again. I am on 2024.1.5 now and am getting correct reporting.

**Comment by boomam** [comment]
Unfortunately there is no clean way to remove the integration prior to removing it from HA, as the 'delete' button is missing from the integration for some reason.  

The methodology i used was to  - 
1) remove the files from the `custom_components` directory - _note, it doesn't let you remove the directory at this point._
2) force remove the integration in HACs
3) restart Home Assistant
4) verify the component directory is now gone.
5) go to HACs, search and install again.
6) prior to restarting HA, verify the files and directory have returned.
7) restart HA
8) re-add and re-setup Integration.
9) quickly go to integrations, find the 'southern company HACS' integration prior to starting, click into it.
10) delete the devices and entities from the three dots - _note, this should be possible without doing all this, but for some reason its not!_
11) go back to intergrations page.
12) add the integration afresh _- this time it now shows the tooltips/descriptions for username/password_
13) notice that it still fails on login with an auth error (even though the username/password *are* correct).
14) go to southern website and do a reset.
15) attempt again

At this point it works again.
No idea why it requires a password reset to start working when the password otherwise works?

**Comment by jprost98** [comment]
My password needed to be reset when I logged in to GA Power to view my info since the integration was "down". So it's hard to tell if it was the integration messing up or Southern Company requiring a mandatory password reset.

**Comment by InTheDaylight14** [comment]
Looks like the required password reset is the only issue. I left my integration unchanged, updated my GA power password through the browser, and then reconfigured the integration and was all set.

**Comment by dcsim0n** [comment]
Checking in here. I think this was resolved in the southern-company-api here: 
 https://github.com/Southern-Company-HA/southern_company_api/pull/14

I think this can be closed.
