### ISSUE TITLE
Home Assistant 2024.6.3  issued started : Failed updating jwt token

### ISSUE THREAD

**Issue by faspina** [Southern-Company-HA/southern-company-hacs#80]
## Version of the custom_component

Latest versions 

## Describe the bug

Suddently stopped working, tried logging in again, credentials are accepted but getting 
Failed updating jwt token

## Debug log

Nothing in the debug log 

```text

Add your logs here.

```

**Comment by kid-pro-kuo** [comment]
+1

**Comment by Lash-L** [comment]
@dcsim0n do you have a chance to take a look at this?

**Comment by dcsim0n** [comment]
It may be a couple days. I’ll add a reminder to take a look ASAP

Dana Simmons
https://linkedin.com/in/dcsimon
KN4BEV

**Comment by bfnpmsz** [comment]
Having the same problem here.  "Failed updating jwt token"

**Comment by ccallahan** [comment]
Any updates on this yet?

**Comment by dcsim0n** [comment]
I looked at it briefly in my dev environment. When sending the auth request
the jwt token isn’t found in the response. It seems likely that the
southern company website changed  and HA needs to change to. I’ll spend
some more time looking at it later this week.

Dana Simmons
https://linkedin.com/in/dcsimon
KN4BEV

**Comment by rixth** [comment]
@Lash-L Has the HA integration been updated with this fix? There looks to be a failing build on the API repo, not sure if it went out or not.

**Comment by Lash-L** [comment]
A new version should have been pushed now.

**Comment by mdb17** [comment]
I am getting this error running 1.0.0
